# Generated by Django 6.0.1 on 2026-03-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('total_rooms', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('hall_description', models.TextField(db_column='Hall_DESCRIPTION')),
                ('accomodation_cost', models.CharField(blank=True, db_column='ACCOMODATION_COST', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Halls',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testdbModel.hall')),
            ],
            options={
                'verbose_name_plural': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('current_occupants', models.IntegerField()),
                ('room_status', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testdbModel.hall')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'unique_together': {('hall', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('matric_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(max_length=6)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('house_address', models.TextField(blank=True, null=True)),
                ('denomination', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hall_selected', models.ForeignKey(blank=True, db_column='hall_selected', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testdbModel.hall')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testdbModel.room')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('payment_reference', models.CharField(max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField()),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('matric_number', models.ForeignKey(db_column='matric_number', on_delete=django.db.models.deletion.DO_NOTHING, to='testdbModel.student', to_field='matric_number')),
            ],
            options={
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('matric_number', models.ForeignKey(db_column='matric_number', on_delete=django.db.models.deletion.DO_NOTHING, to='testdbModel.student', to_field='matric_number')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('allocation_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testdbModel.receipt')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testdbModel.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testdbModel.student')),
            ],
            options={
                'verbose_name_plural': 'Allocation',
                'unique_together': {('student', 'status')},
            },
        ),
    ]
