# Generated by Django 6.0.1 on 2026-02-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdbModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'managed': True},
        ),
    ]
