# Generated by Django 6.0.1 on 2026-03-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdbModel', '0002_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'managed': False, 'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': False},
        ),
    ]
