# Generated by Django 6.0.1 on 2026-03-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdbModel', '0003_alter_log_options_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='allocation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
